version: 2
jobs:
  choice:
    docker:
      - image: opspresso/builder
    working_directory: /tmp/workspace
    steps:
      - checkout
      - run:
          name: Check Charts Versions
          command: ./choice.sh

workflows:
  version: 2
  apply:
    jobs:
      - choice
  nightly:
    jobs:
      - choice
    triggers:
      - schedule:
          cron: "50 2 * * *"
          filters:
            branches:
              only:
                - master
